daysUntilStale: 21

daysUntilClose: 7

onlyLabels: []

exemptProjects: true

exemptMilestones: true

exemptAssignees: false

staleLabel: stale

markComment: >
  This pull request has been automatically marked as stale cause it has not have
  recent activity. It will be closed in 7 days if not further activity occurs.
  Thank you for you contirbutions!!!.

closeComment: >
  This pull request has been closed because it has no recent activity.
  Fell free to re-open this pull request if you wish to still contribute thiese changes.
  Thank you for you contributions!!!.

limitPerRun: 30

only: pulls
