name: Building For x86 Mac

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps Installing
      run: brew install llvm i686-elf-gcc i686-elf-binutils ninja nasm
    
    - name: GN Installing
      run: |
        wget https://chrome-infra-packages.appspot.com/dl/gn/gn/mac-amd64/+/latest
        unzip latest
        mv gn /usr/local/bin
        
    - name: Create Build Environment
      run: ./build.sh
      