name: Building For x86 Ubutnu 20.04

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  bench:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Deps Installing
        run: |
          sudo apt-get update
          sudo apt install -y llvm e2fsprogs qemu-system-i386 qemu-utils fuseext2 ninja-build nasm
          pip3 install tabulate termcolor

      - name: GN Installing
        run: |
          wget https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/latest
          unzip latest
          sudo mv gn /usr/local/bin

      - name: Building
        run: |
          ./build.sh