name: Building For ARM Mac

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps Installing
      run: |
        brew install llvm ninja nasm
        brew tap pranaOS/homebrew-formulae-arm-gcc
        brew install pranaOS/homebrew-formulae-arm-gcc/arm-none-eabi-gcc
    
    - name: GN Installing
      run: |
        wget https://chrome-infra-packages.appspot.com/dl/gn/gn/mac-amd64/+/latest
        unzip latest
        mv gn /usr/local/bin
        
    - name: Create GNU Build Environment
      run: ./build.sh

    - name: Cleaning GNU Build Environment
      run: rm -rf out