name: Checking code formatting linux

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check codestyle linux
        shell: bash
        run: |
          sudo apt-get install clang-format
          find ./ -iname '*.h' -o -iname '*.cpp' -o -iname '*.c'
